FROM 172.16.85.146:8800/centos:7
#FROM centos7.2
#COPY target/demo /usr/local/tomcat/webapps/ROOT/
#ADD target/lib /data/lib
#ADD start.sh /data/
#ADD lib/jdk-1.8.0_77-2.el6.x86_64.rpm /jdk-1.8.0_77-2.el6.x86_64.rpm
#RUN rpm -ivh /jdk-1.8.0_77-2.el6.x86_64.rpm
#ENV JAVA_HOME /usr/local/jdk1.8.0_77
#ENV PATH $PATH:$JAVA_HOME/bin
#RUN chmod +x /data/start.sh
#CMD ["start.sh"]